"""risk_signals_and_rules

Revision ID: 2003ae7fab29
Revises: b4a35392d846
Create Date: 2026-09-17 12:40:46.073099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '2003ae7fab29'
down_revision: Union[str, None] = 'b4a35392d846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_rules_name_version', 'risk_rules', ['name', 'version'], unique=True)
    op.create_table('risk_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_available_at'), 'risk_signals', ['available_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_signal_type'), 'risk_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_risk_signals_source'), 'risk_signals', ['source'], unique=False)
    op.create_index(op.f('ix_risk_signals_transaction_id'), 'risk_signals', ['transaction_id'], unique=False)
    op.create_table('rule_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rules.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluations_evaluated_at'), 'rule_evaluations', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_rule_id'), 'rule_evaluations', ['rule_id'], unique=False)
    op.create_index('ix_rule_evaluations_rule_transaction', 'rule_evaluations', ['rule_id', 'transaction_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_transaction_id'), 'rule_evaluations', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_evaluations_transaction_id'), table_name='rule_evaluations')
    op.drop_index('ix_rule_evaluations_rule_transaction', table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_rule_id'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_evaluated_at'), table_name='rule_evaluations')
    op.drop_table('rule_evaluations')
    op.drop_index(op.f('ix_risk_signals_transaction_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_source'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_signal_type'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_available_at'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index('ix_risk_rules_name_version', table_name='risk_rules')
    op.drop_table('risk_rules')
    # ### end Alembic commands ###
